### ISSUE TITLE
I want to use as less LIVE-Qualcomm video sequences as possible to run the demo.

### ISSUE THREAD

**Issue by harlanc** [jarikorhonen/nr-vqa-consumervideo#2]
I saw that the LIVE-Qualcomm video sequences' size is about 270G, my computer's capacity only has 256G, so can I use less sequences to run your algorithm?

**Comment by harlanc** [comment]
It is Ok to run the algorithm with our own sequences. But has another question, what's the unBiasedMOS and biasedMOS variables mean?I cannot understand they are fixed values in a mat file in your demo, but not some calculated results.And could you have a more detailed description on how to predict a new video sequence?

The next are our results:

After running the compute_features_example.m, we got a csv file whose values are as follows:

![image](https://user-images.githubusercontent.com/10411078/77150124-1f59af80-6ace-11ea-9ac4-bd958dedab28.png)

After running nr_vqm_train_and_validate_example.py , it generates a pic as follows:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/10411078/77150159-37c9ca00-6ace-11ea-8ebe-b7ae4fd37658.png">

Maybe the unBiasedMOS and biasedMOS variables are not correct.

And when these two steps are finished, how to predict a new one? Thank you.

**Comment by jarikorhonen** [comment]
You can of course train the model using less sequences, but basically, more sequences for training, the more accurate the model will be. I am not the right person to answer the question about unBiasedMOS and biasedMOS, I suggest reading the paper by D. Ghadiyaram et al.; unBiasedMOS gives better results, so I suggest using it.

It looks like you are only using few sequences for training and four for testing, so the results cannot be expected to be very good.

If you want to predict the results for a new video sequence, you need to first compute the features for your video file in Matlab and save them in a file, for example assuming resolution 640x360 and frame rate 30 fps:

    reso = [640 360]; fr = 30;
    features = compute_nrvqa_features('myvideo.yuv', reso, fr);
    csvwrite('myvideo_features.csv',[reso(1)/1920 fr/30 features]);

You have to reimplement the Python script, but I think a quick way to test is to add the following lines at line 75 in nr_vqm_train_and_validate_example.py:

    df = pandas.read_csv("myvideo_features.csv", skiprows=[], header=None)       
    x = df.values
    predictedMOS = model.predict(x)
    print('Predicted MOS: ',predictedMOS);

Note that I haven't tested that, but I hope the idea is clear. Also note that if you don't change the number of training sets in the loop on line 89, the process is repeated 100 times. I would suggest changing the code so that you use all the features stored in LIVE_features.csv for training.
