### ISSUE TITLE
Question in the code

### ISSUE THREAD

**Issue by stillbetter** [jarikorhonen/nr-vqa-consumervideo#3]
Hi Jari,thanks for the code.

I have a quesition when reproducing the model. I find, besides feature #1 to #75, the biased MOS and unbiased MOS were also included. But whats's the meaning of the aspect ratio？

`fprintf(fid_ftr, '%2.2f, %2.2f,%0.2f,%0.2f', ...
            data.qualcommSubjectiveData.unBiasedMOS(z), ...
            data.qualcommSubjectiveData.biasedMOS(z), reso(1)/1920, 1);`

 And I find no where need these two nums in `nr_vqm_train_and_validate_example.py`

I'm not sure if I don't understand the code well, or you do need this two nums as feature?

Thanks!

**Comment by jarikorhonen** [comment]
Hi, it's not aspect ratio, it's just an indicator of the resolution. It could be meaningful for datasets with videos with different resolutions, but I don't think it has very large impact, so it could be also left out.

For the meaning of biased and unbiased MOS, I recommend reading the paper about Live dataset. Unbiased MOS gives better results, but I tested the method with both, that's why they are both included.
